// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Change university password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Change password",
                "parameters": [
                    {
                        "description": "Password change request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Login with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "University login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Logout user (client should remove token)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get currently logged-in university details",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a new JWT token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Refresh token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/certificates/batch-anchor": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Anchor multiple certificates to blockchain using Merkle tree and optionally send emails to students",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Certificates"
                ],
                "summary": "Anchor certificates to blockchain",
                "parameters": [
                    {
                        "description": "Batch anchor request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BatchAnchorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.BatchAnchorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/certificates/batch-csv": {
            "post": {
                "description": "Upload CSV file to issue multiple certificates at once",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "Bulk issue certificates from CSV",
                "parameters": [
                    {
                        "type": "file",
                        "description": "CSV file with student data",
                        "name": "csv_file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "University ID",
                        "name": "university_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "University password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/certificates/bulk-download": {
            "get": {
                "description": "Download all certificates for a university as a ZIP file",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/zip"
                ],
                "tags": [
                    "Certificates"
                ],
                "summary": "Bulk download certificates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "University ID",
                        "name": "university_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/certificates/issue": {
            "post": {
                "description": "Issue a certificate for a student with PDF and IPFS storage",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "Issue a single certificate",
                "parameters": [
                    {
                        "description": "Certificate details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.IssueCertificateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/certificates/{certID}": {
            "get": {
                "description": "Retrieve certificate information by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "Get certificate details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Certificate ID",
                        "name": "certID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/certificates/{certID}/download": {
            "get": {
                "description": "Download the PDF certificate from IPFS",
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "certificates"
                ],
                "summary": "Download certificate PDF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Certificate ID",
                        "name": "certID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/certificates/{id}/download": {
            "get": {
                "description": "Download a single certificate PDF by ID",
                "produces": [
                    "application/pdf"
                ],
                "tags": [
                    "Certificates"
                ],
                "summary": "Download certificate PDF",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Certificate ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/university/register": {
            "post": {
                "description": "Register a university with domain and generate Cardano wallet",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "university"
                ],
                "summary": "Register a new university",
                "parameters": [
                    {
                        "description": "University registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/university/{id}/domain-proof": {
            "get": {
                "description": "Get the verification file content for domain proof",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "university"
                ],
                "summary": "Get domain verification proof",
                "parameters": [
                    {
                        "type": "string",
                        "description": "University ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.DomainVerificationResponse"
                        }
                    }
                }
            }
        },
        "/university/{id}/verify-domain": {
            "post": {
                "description": "Verify that the university owns the domain by checking the verification file",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "university"
                ],
                "summary": "Verify domain ownership",
                "parameters": [
                    {
                        "type": "string",
                        "description": "University ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/verify/blockchain/{certID}": {
            "get": {
                "description": "Get blockchain explorer links for a certificate",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "verification"
                ],
                "summary": "Get blockchain information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Certificate ID",
                        "name": "certID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.BatchAnchorRequest": {
            "type": "object",
            "required": [
                "password",
                "university_id"
            ],
            "properties": {
                "max_certs": {
                    "description": "Optional, default 1000",
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "send_emails": {
                    "type": "boolean"
                },
                "university_id": {
                    "type": "string"
                }
            }
        },
        "handlers.BatchAnchorResponse": {
            "type": "object",
            "properties": {
                "cardano_txid": {
                    "type": "string",
                    "example": "f75eac8ac7b3..."
                },
                "certificates": {
                    "type": "integer",
                    "example": 10
                },
                "cost": {
                    "type": "string",
                    "example": "0.17 ADA (~$0.08)"
                },
                "cost_per_cert": {
                    "type": "string",
                    "example": "$0.008000"
                },
                "email_errors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "email_warning": {
                    "type": "string",
                    "example": "2 emails failed to send"
                },
                "emails_sent": {
                    "type": "integer",
                    "example": 10
                },
                "explorer_url": {
                    "type": "string",
                    "example": "https://preview.cardanoscan.io/transaction/..."
                },
                "merkle_root": {
                    "type": "string",
                    "example": "abc123def456..."
                },
                "message": {
                    "type": "string",
                    "example": "✅ 10 certificates anchored and 10 emails sent!"
                },
                "network": {
                    "type": "string",
                    "example": "preview"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "wallet": {
                    "type": "string",
                    "example": "addr_test1..."
                }
            }
        },
        "handlers.ChangePasswordRequest": {
            "type": "object",
            "required": [
                "current_password",
                "new_password"
            ],
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "handlers.DomainVerificationResponse": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "file_content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "file_path": {
                    "type": "string"
                },
                "instructions": {
                    "type": "string"
                },
                "university_id": {
                    "type": "string"
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "handlers.IssueCertificateRequest": {
            "type": "object",
            "required": [
                "degree",
                "password",
                "student_email",
                "student_name",
                "university_id"
            ],
            "properties": {
                "degree": {
                    "type": "string"
                },
                "gpa": {
                    "type": "number"
                },
                "password": {
                    "type": "string"
                },
                "student_email": {
                    "type": "string"
                },
                "student_name": {
                    "type": "string"
                },
                "university_id": {
                    "type": "string"
                }
            }
        },
        "handlers.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "handlers.LoginResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                },
                "university": {
                    "$ref": "#/definitions/handlers.UniversityInfo"
                }
            }
        },
        "handlers.RegisterRequest": {
            "type": "object",
            "required": [
                "domain",
                "email",
                "name",
                "password"
            ],
            "properties": {
                "domain": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 12
                }
            }
        },
        "handlers.UniversityInfo": {
            "type": "object",
            "properties": {
                "cardano_address": {
                    "type": "string"
                },
                "domain": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_verified": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "Certificate System API",
	Description:      "Blockchain-based certificate issuance and verification system",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
